#!/bin/sh

set -e

DESKTOP_CONFIG_FILE_NAME="terminal-package-update.desktop"
DESKTOP_AUTOSTART_DIR="/home/${SUDO_USER}/.config/autostart"

rm -f "${DESKTOP_AUTOSTART_DIR}/${DESKTOP_CONFIG_FILE_NAME}"
